openapi: 3.0.3
info:
  title: OpenSID-API
  description: ''
  version: 1.0.0
servers:
  -
    url: 'https://opensid-api.sandboxindonesia.id'
paths:
  /:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'Lumen (8.3.1) (Laravel Components ^8.0)'
      tags:
        - Endpoints
      security: []
  /v1/register:
    post:
      summary: 'Register a new user.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'The name of the user.'
                  example: '"barenglor"'
                email:
                  type: email
                  description: 'The user email.'
                  example: '"test@gmail.com"'
                password:
                  type: string
                  description: 'Used to authenticate the user. Min: 6'
                  example: porro
              required:
                - name
                - email
                - password
      security: []
  /v1/login:
    post:
      summary: 'Get the authenticated User.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: email
                  description: 'The user email.'
                  example: '"test@gmail.com"'
                password:
                  type: string
                  description: 'Used to authenticate the user.'
                  example: ipsa
              required:
                - email
                - password
      security: []
  /v1/logout:
    post:
      summary: 'Log the user out (Invalidate the token).'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
  /v1/penduduk:
    get:
      summary: 'Display a listing of the Penduduk resource.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     \"data\": [\n         {\n             \"id\": 1,\n             \"created_at\": \"2019-05-28T15:45:28.000000Z\",\n             \"updated_at\": \"2020-07-30T04:30:21.000000Z\",\n             \"deleted_at\": null,\n             \"nik\": \"5201142005716996\",\n             \"chip_ektp\": 0,\n             \"nama\": \"AHLUL\",\n             \"tgl_lahir\": \"1970-05-20\",\n             \"tempat_lahir\": \"MANGSIT\",\n             \"jk\": \"LAKI-LAKI\",\n             \"alamat_sekarang\": \"\",\n             \"agama\": \"ISLAM\",\n             \"pendidikan\": \"TAMAT SD / SEDERAJAT\",\n             \"pekerjaan\": \"TUKANG BATU\",\n             \"status_kawin\": \"KAWIN\",\n             \"status_penduduk\": null,\n             \"kewarganegaraan\": \"WNI\",\n             \"anak_ke\": 0,\n             \"golongan_darah\": \"TIDAK TAHU\",\n             \"status_dalam_keluarga\": null,\n             \"no_paspor\": \"\",\n             \"suku\": null,\n             \"potensi_diri\": null,\n             \"no_hp\": null,\n             \"nik_ayah\": \"\",\n             \"nik_ibu\": \"\",\n             \"nama_ayah\": \"ARFAH\",\n             \"nama_ibu\": \"RAISAH\",\n             \"tgl_exp_paspor\": null,\n             \"akta_lahir\": \"\",\n             \"akta_kawin\": \"\",\n             \"tgl_kawin\": null,\n             \"akta_cerai\": \"\",\n             \"tgl_cerai\": null,\n             \"kelainan_fisik\": null,\n             \"cacat\": null,\n             \"foto\": \"\",\n             \"pass_field\": null,\n             \"status_covid\": null,\n             \"status_vaksin\": null,\n             \"status_stunting\": null,\n             \"created_by\": 0,\n             \"updated_by\": 1,\n             \"deleted_by\": null\n         },\n     ],\n}"
      tags:
        - Endpoints
  '/v1/penduduk/{id}':
    get:
      summary: 'Show one of the Penduduk resource.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    created_at: '2019-05-28T15:45:28.000000Z'
                    updated_at: '2020-07-30T04:30:21.000000Z'
                    deleted_at: null
                    nik: '5201142005716996'
                    chip_ektp: 0
                    nama: AHLUL
                    tgl_lahir: '1970-05-20'
                    tempat_lahir: MANGSIT
                    jk: LAKI-LAKI
                    alamat_sekarang: ''
                    agama: ISLAM
                    pendidikan: 'TAMAT SD / SEDERAJAT'
                    pekerjaan: 'TUKANG BATU'
                    status_kawin: KAWIN
                    status_penduduk: null
                    kewarganegaraan: WNI
                    anak_ke: 0
                    golongan_darah: 'TIDAK TAHU'
                    status_dalam_keluarga: null
                    no_paspor: ''
                    suku: null
                    potensi_diri: null
                    no_hp: null
                    nik_ayah: ''
                    nik_ibu: ''
                    nama_ayah: ARFAH
                    nama_ibu: RAISAH
                    tgl_exp_paspor: null
                    akta_lahir: ''
                    akta_kawin: ''
                    tgl_kawin: null
                    akta_cerai: ''
                    tgl_cerai: null
                    kelainan_fisik: null
                    cacat: null
                    foto: ''
                    pass_field: null
                    status_covid: null
                    status_vaksin: null
                    status_stunting: null
                    created_by: 0
                    updated_by: 1
                    deleted_by: null
                properties:
                  data:
                    type: object
                    example:
                      id: 1
                      created_at: '2019-05-28T15:45:28.000000Z'
                      updated_at: '2020-07-30T04:30:21.000000Z'
                      deleted_at: null
                      nik: '5201142005716996'
                      chip_ektp: 0
                      nama: AHLUL
                      tgl_lahir: '1970-05-20'
                      tempat_lahir: MANGSIT
                      jk: LAKI-LAKI
                      alamat_sekarang: ''
                      agama: ISLAM
                      pendidikan: 'TAMAT SD / SEDERAJAT'
                      pekerjaan: 'TUKANG BATU'
                      status_kawin: KAWIN
                      status_penduduk: null
                      kewarganegaraan: WNI
                      anak_ke: 0
                      golongan_darah: 'TIDAK TAHU'
                      status_dalam_keluarga: null
                      no_paspor: ''
                      suku: null
                      potensi_diri: null
                      no_hp: null
                      nik_ayah: ''
                      nik_ibu: ''
                      nama_ayah: ARFAH
                      nama_ibu: RAISAH
                      tgl_exp_paspor: null
                      akta_lahir: ''
                      akta_kawin: ''
                      tgl_kawin: null
                      akta_cerai: ''
                      tgl_cerai: null
                      kelainan_fisik: null
                      cacat: null
                      foto: ''
                      pass_field: null
                      status_covid: null
                      status_vaksin: null
                      status_stunting: null
                      created_by: 0
                      updated_by: 1
                      deleted_by: null
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: ''
        example: doloremque
        required: true
        schema:
          type: string
  /v1/keluarga:
    get:
      summary: 'Display a listing of the Keluarga resource.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            text/plain:
              schema:
                type: string
                example: "{\n     \"data\": [\n          {\n              \"id\": 1,\n                 \"kepala_keluarga\": {\n                     \"nama\": \"AHLUL\",\n                     \"nik\": \"5201142005716996\"\n                  },\n              \"alamat_lengkap\": null,\n              \"objek_alamat\": {\n                  \"id\": 1,\n                  \"rt\": \"0\",\n                  \"rw\": \"0\",\n                  \"dusun\": \"MANGSIT\",\n                  \"id_kepala\": 0,\n                  \"lat\": \"\",\n                  \"lng\": \"\",\n                  \"zoom\": 0,\n                  \"path\": \"\",\n                  \"map_tipe\": \"\",\n                  \"warna\": null,\n                  \"urut\": null,\n                  \"urut_cetak\": null\n              },\n              \"no_kk\": \"5201140104126994\",\n              \"jalan_blok\": null,\n              \"kode_pos\": \"83355\",\n              \"status_kesejahteraan\": \"Keluarga Pra Sejahtera\",\n              \"penghasilan\": null,\n              \"status_kk\": null,\n              \"status_pkh\": null,\n              \"status_blt\": null,\n              \"status_bansos\": null,\n              \"desa\": \"5201142005\",\n              \"menguasai\": null\n          }\n     ],\n}"
      tags:
        - Endpoints
  '/v1/keluarga/{id}':
    get:
      summary: 'Show one of the Keluarga resource.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 1
                    kepala_keluarga:
                      nama: AHLUL
                      nik: '5201142005716996'
                    alamat_lengkap: null
                    objek_alamat:
                      id: 1
                      rt: '0'
                      rw: '0'
                      dusun: MANGSIT
                      id_kepala: 0
                      lat: ''
                      lng: ''
                      zoom: 0
                      path: ''
                      map_tipe: ''
                      warna: null
                      urut: null
                      urut_cetak: null
                    no_kk: '5201140104126994'
                    jalan_blok: null
                    kode_pos: '83355'
                    status_kesejahteraan: 'Keluarga Pra Sejahtera'
                    penghasilan: null
                    status_kk: null
                    status_pkh: null
                    status_blt: null
                    status_bansos: null
                    desa: '5201142005'
                    menguasai: null
                properties:
                  data:
                    type: object
                    example:
                      id: 1
                      kepala_keluarga:
                        nama: AHLUL
                        nik: '5201142005716996'
                      alamat_lengkap: null
                      objek_alamat:
                        id: 1
                        rt: '0'
                        rw: '0'
                        dusun: MANGSIT
                        id_kepala: 0
                        lat: ''
                        lng: ''
                        zoom: 0
                        path: ''
                        map_tipe: ''
                        warna: null
                        urut: null
                        urut_cetak: null
                      no_kk: '5201140104126994'
                      jalan_blok: null
                      kode_pos: '83355'
                      status_kesejahteraan: 'Keluarga Pra Sejahtera'
                      penghasilan: null
                      status_kk: null
                      status_pkh: null
                      status_blt: null
                      status_bansos: null
                      desa: '5201142005'
                      menguasai: null
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: id
        description: ''
        example: doloribus
        required: true
        schema:
          type: string
  /v1/refresh:
    put:
      summary: 'Get the token array structure.'
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
